services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Force\DBDoc\Controller\:
        resources: '../../Controller'
        tags: ['controller.service_arguments']
        